# Generated by Django 5.2.5 on 2025-08-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latin', models.CharField(max_length=100, unique=True)),
                ('arabic_script', models.CharField(blank=True, max_length=100)),
                ('old_turkic', models.CharField(blank=True, max_length=100)),
                ('translation_en', models.TextField(blank=True)),
                ('translation_fa', models.TextField(blank=True)),
            ],
        ),
    ]
