# Generated by Django 5.2.5 on 2025-08-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
